### ISSUE TITLE
Disciplinas dependentes e amigas da UFC

### ISSUE THREAD

**Issue by ryukinix** [datascience-ufc/knowledge-graph#2]

**Comment by SamuelHericles** [comment]
Programação Computacional
Matemática Discreta
Cálculo I

Técnicas de Programação
Álgebra Linear
Probabilidade e Estatística
Cálculo II

Estrutura de dados
Métodos Numéricos
Cálculo vetorial

Variáveis Complexas
Processos Estocásticos
Sistemas Lineares
Inteligência computacional
Banco de Dados
Processamento Digital de Sinais

**Comment by ryukinix** [comment]
Após estruturar essa informação no repositório podemos fechar essa tarefa.

**Comment by Lucas-Leite** [comment]
GUIA PARA INICIANTES EM DATA SCIENCE

O entusiasta na área deve ficar ciente que é fundamental dominar ou estar disposto a aprender em especial programação, pensamento lógico, conhecimento em banco de dados e saber trabalhar com números.

Se você é um estudante da Universidade Federal do Ceará segue abaixo as disciplinas que irá te auxiliar diretamente ou indiretamente durante o processo de aprendizagem.

Pré-requisitos diretos baseado na grade de 2006.2 do Curso de Engenharia da Computação - UFC SOBRAL

SBL0086 - Programação Computacional
ECO0025 - Matemática Discreta
SBL0057 - Cálculo I

ECO0015 - Técnicas de Programação
SBL0056 - Álgebra Linear
SBL0084 - Probabilidade e Estatística
SBL0058 - Cálculo II

ECO0016 - Estrutura de dados
SBL0081 - Métodos Numéricos
SBL0059 - Cálculo vetorial

SBL0095 - Variáveis Complexas
ECO0076 - Processos Estocásticos
SBL0091 - Sistemas Lineares
SBL0080 - Inteligência computacional
ECO0031 - Banco de Dados
SBL0085 - Processamento Digital de Sinais

EXTRA GRADE
Inglês
Machine learning
OBS: Sugestão de linguagens R e Python

Pré-requisitos indiretos baseado na grade de 2006.2 do Curso de Engenharia da Computação - UFC SOBRAL

SBL0071 - Engenharia Economica
SBL0076	- Fundamentos de Economia
SBL0077 - Fundamentos de Administração

Caso pertença a outra graduação ou não curse nenhuma, segue links que poderam te ajudar nesse processo de aderir conhecimento:

http://datascienceacademy.com.br/blog/cientista-de-dados-por-onde-comecar-em-8-passos/

https://medium.com/data-science-brigade/como-aprender-data-science-de-gra%C3%A7a-nas-melhores-universidades-do-mundo-60a76a3af887

**Comment by ryukinix** [comment]
Ficou bacana @Lucas-Leite !! Obrigado!

**Comment by ryukinix** [comment]
Adicionei o arquivo requisitos.txt no repositório, fechando isso aqui.
